name: Deploy to Contabo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy to Contabo via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USER }}
          key: ${{ secrets.CONTABO_SSH_KEY }}
          script: |
            cd reetuurn-backend
            git reset --hard
            git pull origin main
            npm install --production
            pm2 reload reetuurn-backend || pm2 start npm --name "reetuurn-backend" -- run start
            pm2 save
